config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :pets
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/pet.rb
class Pet < ApplicationRecord
  validate :color, :species
  validate :name, :last_seen
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: %i[show edit update destroy]

  def index
    @pets = Pet.all
  end

  def show
  end

  def new
    @pet = Pet.new
  end

  def create
    @pet = Pet.new(pet_params)
    @pet.save
    redirect_to pets_path
  end

  def edit
  end

  def update
    @pet.update(pet_params)
    @pet.save
  end

  def destroy
    @pet.destroy
  end

  private

  def set_pet
    @pet = Pet.find(params[:id])
  end

  def pet_params
    params.require(:pet).permit(:name, :color, :species, :last_seen)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Emmas Pets Livecode</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
  <footer>
  </footer>
</html>

app/views/pets/index.html.erb
<h1>All our lovely Pets🐈</h1>

<ul>
  <% @pets.each do |pet| %>
  <h4><%= pet.name %></h4>
  <% end %>
</ul>

<%= link_to 'Add a new missing Pet', new_pet_path %>

app/views/pets/new.html.erb
<div class="container">
  <h1>Let's find your pet! </h1>
  <%= simple_form_for @pet do |f| %>
    <%= f.input :name %>
    <%= f.input :color %>
    <%= f.input :species %>
    <%= f.input :last_seen %>
    <%= f.button :submit %>
  <% end %>
</div>

app/views/pets/show.html.erb
<h1>Here is our beautiful: <%= @pet.name  %> </h1>

  <p>The pet is a <%= @pet.species %></p>
  <p>and has a color of: <%= @pet.color %></p>
  <p>The pet was last seen <%= @pet.last_seen %> days ago</p>